name: mb-ds-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - xgboost=2.0.3
  - statsmodels=0.14.1
  - scipy
  - shap
  - plotly
  - pip:
      - prophet
